language: android

branches:
  only:
    - master

script: 
- cd SimpleToDo/
- ./gradlew clean assembleDebug

android:
  components:
      - platform-tools
      - tools
      - build-tools-25.0.2
      - android-25
      - extra-android-m2repository